# Generated by Django 6.0.6 on 2026-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_options_remove_order_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
