line-length = 79

[lint]
extend-select = [
    "F401", 
    "F841",  
    "F821",  
    "RET501",  
    "RET502",  
    "RET503",  
    "RET504",  
    "B006", 
    "B010",  
    "B020",  
    "B023", 
    "SIM102",  
    "SIM103",  
    "SIM105",  
    "UP035",  
    "I001",  
    "I002",  
    ]
ignore = [
    "RUF012", 
    "B017",
    "BLE001",
    "S110"
]