# Generated by Django 6.0.6 on 2026-08-21 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_size_options_size_slug_alter_size_name_and_more"),
    ]

    operations = []
