# Generated by Django 6.0.6 on 2026-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_populate_size_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="slug",
            field=models.SlugField(
                blank=True, unique=True, verbose_name="Слаг"
            ),
        ),
    ]
